import tkinter as tk
from tkinter import ttk
from tkinter.ttk import *
from tkinter import *
import ttkbootstrap as ttkb
from PIL import ImageTk, Image

root = tk.Tk()
style = ttkb.Style("morph")
root.title("Aspen设置")
root.geometry("800x550")
note = Notebook(root, width=800, height=550)

# 添加标题图片
img1 = Image.open(r"F:\AspenPlus-Python-Interface-main\AspenPlus-Python-Interface-main\AspenProject\标题.png")
photo = ImageTk.PhotoImage(img1)
imglabel = Label(root, image=photo)
imglabel.place(x=0, y=0)

fr1 = Frame()
fr2 = Frame()
fr3 = Frame()

note.place(x=0, y=70)

note.add(fr1, text='input')
note.add(fr2, text='result')
note.add(fr3, text='...')

labFrame3 = Labelframe(fr2, text='MIXED Substream')  # 此处为避免放不下控件不能设置固定的宽高，但可以通过控制控件大小来控制宽高
labFrame3.place(x=120, y=20)
labFrame4 = Labelframe(fr2, text='Flows ＆ Fractions')  # 此处为避免放不下控件不能设置固定的宽高，但可以通过控制控件大小来控制宽高
labFrame4.place(x=110, y=240)

label = tk.Label(labFrame3, text="Temperature：", font="等线")
label.grid(row=0, column=0, sticky='w')
label = tk.Label(labFrame3, text="-50")
label.grid(row=0, column=1, sticky='w')
label = tk.Label(labFrame3, text="°C", font="等线")
label.grid(row=0, column=2, sticky='w')
label = tk.Label(labFrame3, text="Pressure：", font="等线")
label.grid(row=1, column=0, sticky='w')
label = tk.Label(labFrame3, text="30")
label.grid(row=1, column=1, sticky='w')
label = tk.Label(labFrame3, text="bar", font="等线")
label.grid(row=1, column=2, sticky='w')
label = tk.Label(labFrame3, text="Molar Vapor Fraction：", font="等线")
label.grid(row=2, column=0, sticky='w')
label = tk.Label(labFrame3, text="0")
label.grid(row=2, column=1, sticky='w')
label = tk.Label(labFrame3, text="Molar Liquid Fraction：", font="等线")
label.grid(row=3, column=0, sticky='w')
label = tk.Label(labFrame3, text="1")
label.grid(row=3, column=1, sticky='w')
label = tk.Label(labFrame3, text="Molar Solid Fraction：", font="等线")
label.grid(row=4, column=0, sticky='w')
label = tk.Label(labFrame3, text="0")
label.grid(row=4, column=1, sticky='w')
label = tk.Label(labFrame3, text="Mass Vapor Fraction：", font="等线")
label.grid(row=5, column=0, sticky='w')
label = tk.Label(labFrame3, text="0")
label.grid(row=5, column=1, sticky='w')
label = tk.Label(labFrame3, text="Mass Liquid Fraction：", font="等线")
label.grid(row=6, column=0, sticky='w')
label = tk.Label(labFrame3, text="1")
label.grid(row=6, column=1, sticky='w')
label = tk.Label(labFrame3, text="Mass Solid Fraction：", font="等线")
label.grid(row=7, column=0, sticky='w')
label = tk.Label(labFrame3, text="0")
label.grid(row=7, column=1, sticky='w')
label = tk.Label(labFrame3, text="            ")
label.grid(row=0, column=3, sticky='w')
label = tk.Label(labFrame3, text="Molar Enthalpy：", font="等线")
label.grid(row=0, column=4, sticky='w')
label = tk.Label(labFrame3, text="-92523")
label.grid(row=0, column=5, sticky='w')
label = tk.Label(labFrame3, text="cal/mol", font="等线")
label.grid(row=0, column=6, sticky='w')
label = tk.Label(labFrame3, text="Mass Enthalpy：", font="等线")
label.grid(row=1, column=4, sticky='w')
label = tk.Label(labFrame3, text="-2141.5")
label.grid(row=1, column=5, sticky='w')
label = tk.Label(labFrame3, text="cal/gm", font="等线")
label.grid(row=1, column=6, sticky='w')
label = tk.Label(labFrame3, text="Molar Entropy：", font="等线")
label.grid(row=2, column=4, sticky='w')
label = tk.Label(labFrame3, text="-20.9864")
label.grid(row=2, column=5, sticky='w')
label = tk.Label(labFrame3, text="cal/mol-K", font="等线")
label.grid(row=2, column=6, sticky='w')
label = tk.Label(labFrame3, text="Mass Entropy：", font="等线")
label.grid(row=3, column=4, sticky='w')
label = tk.Label(labFrame3, text="-0.485743")
label.grid(row=3, column=5, sticky='w')
label = tk.Label(labFrame3, text="cal/gm-K", font="等线")
label.grid(row=3, column=6, sticky='w')
label = tk.Label(labFrame3, text="Molar Density：", font="等线")
label.grid(row=4, column=4, sticky='w')
label = tk.Label(labFrame3, text="0.0256228")
label.grid(row=4, column=5, sticky='w')
label = tk.Label(labFrame3, text="mol/cc", font="等线")
label.grid(row=4, column=6, sticky='w')
label = tk.Label(labFrame3, text="Mass Density：", font="等线")
label.grid(row=5, column=4, sticky='w')
label = tk.Label(labFrame3, text="1.10702")
label.grid(row=5, column=5, sticky='w')
label = tk.Label(labFrame3, text="gm/cc", font="等线")
label.grid(row=5, column=6, sticky='w')
label = tk.Label(labFrame3, text="Enthalpy Flow：", font="等线")
label.grid(row=6, column=4, sticky='w')
label = tk.Label(labFrame3, text="-6390.67")
label.grid(row=6, column=5, sticky='w')
label = tk.Label(labFrame3, text="cal/sec", font="等线")
label.grid(row=6, column=6, sticky='w')
label = tk.Label(labFrame3, text="Average MW：", font="等线")
label.grid(row=7, column=4, sticky='w')
label = tk.Label(labFrame3, text="43.2047")
label.grid(row=7, column=5, sticky='w')

label = tk.Label(labFrame4, text="   ")
label.grid(row=0, column=0)
label = tk.Label(labFrame4, text="Mole Flows(kmol/hr) ", font="等线")
label.grid(row=0, column=1, sticky='w')
label = tk.Label(labFrame4, text="Mole Fractions ", font="等线")
label.grid(row=0, column=2, sticky='w')
label = tk.Label(labFrame4, text="Mass Flows(kg/hr) ", font="等线")
label.grid(row=0, column=3, sticky='w')
label = tk.Label(labFrame4, text="Mass Fractions", font="等线")
label.grid(row=0, column=4, sticky='w')
label = tk.Label(labFrame4, text="Total  ", font="等线")
label.grid(row=1, column=0, sticky='w')
label = tk.Label(labFrame4, text="0.248656")
label.grid(row=1, column=1)
label = tk.Label(labFrame4, text="1")
label.grid(row=1, column=2)
label = tk.Label(labFrame4, text="10.7431")
label.grid(row=1, column=3)
label = tk.Label(labFrame4, text="1")
label.grid(row=1, column=4)
label = tk.Label(labFrame4, text="H2O", font="等线")
label.grid(row=2, column=0, sticky='w')
label = tk.Label(labFrame4, text="0")
label.grid(row=2, column=1)
label = tk.Label(labFrame4, text="0")
label.grid(row=2, column=2)
label = tk.Label(labFrame4, text="0")
label.grid(row=2, column=3)
label = tk.Label(labFrame4, text="0")
label.grid(row=2, column=4)
label = tk.Label(labFrame4, text="N2", font="等线")
label.grid(row=3, column=0, sticky='w')
label = tk.Label(labFrame4, text="0.00577337")
label.grid(row=3, column=1)
label = tk.Label(labFrame4, text="0.0232183")
label.grid(row=3, column=2)
label = tk.Label(labFrame4, text="0.161732")
label.grid(row=3, column=3)
label = tk.Label(labFrame4, text="0.0150545")
label.grid(row=3, column=4)
label = tk.Label(labFrame4, text="CO2", font="等线")
label.grid(row=4, column=0, sticky='w')
label = tk.Label(labFrame4, text="0.233904")
label.grid(row=4, column=1)
label = tk.Label(labFrame4, text="0.940671")
label.grid(row=4, column=2)
label = tk.Label(labFrame4, text="10.2941")
label.grid(row=4, column=3)
label = tk.Label(labFrame4, text="0.958201")
label.grid(row=4, column=4)
label = tk.Label(labFrame4, text="H3N", font="等线")
label.grid(row=5, column=0, sticky='w')
label = tk.Label(labFrame4, text="0")
label.grid(row=5, column=1)
label = tk.Label(labFrame4, text="0")
label.grid(row=5, column=2)
label = tk.Label(labFrame4, text="0")
label.grid(row=5, column=3)
label = tk.Label(labFrame4, text="0")
label.grid(row=5, column=4)
label = tk.Label(labFrame4, text="O2", font="等线")
label.grid(row=6, column=0, sticky='w')
label = tk.Label(labFrame4, text="0.00897904")
label.grid(row=6, column=1)
label = tk.Label(labFrame4, text="0.0361102")
label.grid(row=6, column=2)
label = tk.Label(labFrame4, text="0.287319")
label.grid(row=6, column=3)
label = tk.Label(labFrame4, text="0.0267444")
label.grid(row=6, column=4)


root.mainloop()